### ISSUE TITLE
Add query option "waiting+current+rejected" for translations

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1190]
Currently it is cumbersome/hard/time-consuming to check if a current record is present when someone adds a translation proposal. You need to filter with the original line to find the current line if one exists. That takes a lot of time to do.
Proposal:
Add a new query option "waiting+current+rejected"
Then you should get a list with the waiting records preceded by the rejected, current, waiting in that order.
If no rejected, current lines are found, then only the proposal line should be shown. The example below shows a rejected + waiting record. To get that you need to add the original string
![New_query](https://user-images.githubusercontent.com/28138634/90491339-15e97780-e140-11ea-94b9-bb1ed7c14b05.JPG)

**Comment by naokomc** [comment]
I agree this new filter will speed up the review process.

Currently, I follow the process below to make sure I don't overwrite existing translation by mistake if I'm looking at translations by a user who suggests many translation changes to already Current strings.

* Go to "All" view
* Start from page 1 and go through every page to the end, catching any suggestions for existing ones

I prefer this than using Translation History one by one because there are fewer steps to check each string.
Peter's suggestion makes it even faster because I can ignore Current ones altogether.

**Comment by amieiro** [comment]
@psmits1567 the status filter has been changed from radio buttons to checkboxes, so now you can select these statuses in 3 checkboxes. Is it ok if I close the issue?

![image](https://user-images.githubusercontent.com/1667814/211887572-b0744379-447e-4c3c-978e-1beff05d17a2.png)

**Comment by psmits1567** [comment]
Yes with this possebility we can check suggestions quicker, so you can close it
