### ISSUE TITLE
Improve the way how an active project is highlighted

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1335]
Currently we have small 'Active' label next to the project name. The label is visible in the breadcrumb or the project list if a project has sub-projects.

<img width="307" alt="" src="https://user-images.githubusercontent.com/617637/159120321-9d275703-3cd1-4f13-af59-23bc21dbc12b.png">

Though, the label gets lost in the breadcrumb of a translation set:
<img width="277" alt="" src="https://user-images.githubusercontent.com/617637/159120379-c4bbf005-cc77-4a5d-8ae6-32f562aa7781.png">

Since the number of inactive projects should (hopefully) be higher than the number of active projects I'm thinking of inverting the current display by only showing a label for inactive/archived projects. The 'Archived' label should then always be part of the project item in a breadcrumb, no matter the position.
This should help users to quickly identify if a project is still active.

**Comment by pedro-mendonca** [comment]
Makes sense, only highlight "Archived" projects.

**Comment by amieiro** [comment]
The inactive projects are set at the bottom of the page. We can try two different approaches:

1. Add an opacity to the inactive projects, without removing the "Active" labels for the active projects.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/30404e90-bb41-4407-8489-d316705dfc01)

2. Add an opacity to the inactive projects, removing the "Active" labels for the active projects.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/d188d1a1-d65e-4e84-bcfd-cda80f186b0b)

3. Add an opacity to the inactive projects, removing the "Active" labels for the active projects and adding a new "Inactive" label for each inactive project.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/980d9515-5c88-4b69-a12c-8c5cb1d69661)

For me, the best option is the 3rd.

**Comment by pedro-mendonca** [comment]
To start, the initial suggestion from @ocean90 is about to invert the logic of which projects need to have an extra info.
I agree that is better to invert, showing some "archived" tag as is used in other platforms (eg GitHub). Being the default "active", doesn't need any tag.
Another different issue is the styling, using opacity or not, it's something that could even be customized by the install admin. Is more opinionated discussion.
I would start by removing the "active" adding the "archived", adding some CSS class to the project entry, so that the styling could be further discussed in a more wide design discussion.

**Comment by fxbenard** [comment]
Inversion is a nice move, no need to add activ to all projects we're working on…
Using inactive sounds better than archived for me as if it's archived it doesn't need to be seen on the dashboard…
For the opacity not sure it's needed as well, it might as said by @pedro-mendonca added after.
Let's keep the UI as clean as possible.
A way to remove inactiv projects from the dashboard will be nice
