### ISSUE TITLE
It's possible to add multiple glossary entries for one term/noun/...

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1358]
It's possible to add two different glossary entries for the same word. 
I think this can cause confusion. Especially since we can give more info in the comment box. 

So, I would add a warning when you are trying to add a new glossary term for a word that's already in the glossary.

**Comment by ocean90** [comment]
Hey there, that's by design and allows you to provide different translations based on the context which you can explain in the comment for each translation.

Example:
<img width="353" alt="Bildschirmfoto 2022-03-25 um 11 30 20" src="https://user-images.githubusercontent.com/617637/160104174-6ef25ec9-e3d7-40a0-8cd6-52d593967638.png">
