### ISSUE TITLE
Glossary: Improve performance of parsing translations for adding tooltips 

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1383]
Related: #1377

It seems like `map_glossary_entries_to_translation_originals()` would benefit from some improvements to make it more performant. 
For example [this project](https://translate.wordpress.org/projects/patterns/core/nl-be/default/?filters%5Bterm%5D=mark) on translate.w.org needs around 3.5 - 4 seconds. After adding an early `return $translation;` it only needs 1.1 seconds.

The following part is something that only should only run once per glossary.

https://github.com/GlotPress/GlotPress-WP/blob/5b4adbb41931dd0cbea5957de9c7514cbc96777e/gp-templates/helper-functions.php#L152-L185

I'm wondering if we can move all the sorting and back-reference handling into a new `GP_Glossary` method like `get_entries_for_mapping()` which also handles some caching like already done for `get_entries()`.

This issue is mostly noticeable if a locale has many glossary entries and a user has a high per page setting. Also worth to noting that this always runs twice per string since we have the preview and editor rows.

**Comment by pedro-mendonca** [comment]
Currently every string is being split agains a full list of the Glossary entries. Considering that this list is increasing, it will become a huge work.
What about a first pass to filter those glossary entries, only adding to the glossary terms search (single and multiple words) those which contain at least one word from the string?

Example string:
`The item was permanently deleted.`

Glossary list example:
- item
- permanently deleted
- delete
- post
- page
- remove
- etc

New previous steps:
1) Split string in words
2) Find which exist in the glossary (item, permanently, deleted, delete)

Currently existent step
3) Split the string, but instead of against the full glossary items list, against the limited matching glossary items done in step 2.

Would this save some processing time per string?

**Comment by ocean90** [comment]
I've moved this to the 3.0 milestone as it's harming the performance of translate.wordpress.org. If we can't find a solution we may have to revert #1359 for 3.0 and try it again in 3.1 with [the other glossary related issues](https://github.com/GlotPress/GlotPress/milestone/15).
