### ISSUE TITLE
Minification: Improve workflow for Pull Requests that contain changes to JavaScript files

### ISSUE THREAD

**Issue by akirk** [GlotPress/GlotPress-WP#1587]
Right now, the minified files easily lead to conflicts when another PR with changes to the JS files has been merged. Can we improve this process?

My suggestion:

Remove minified files from develop and only generate and use them upon deploy to WordPress.org. This means we'd delete the minified files from the develop branch, change the `SCRIPT_DEBUG` if condition to add another constant and set this constant before deploying to .org.

e.g. `$suffix = SCRIPT_DEBUG || ! GP_USE_MINIFIED ? '.css' : '.min.css';`

**Comment by pedro-mendonca** [comment]
If is to use a constant, maybe `GP_DEBUG` :)

**Comment by pedro-mendonca** [comment]
Removing the minified files from the develop branch might raise issues on a dev install.

How can GP seamlessly check if it's installed from .org or from a GitHub release link?

Instead of making a complicated process, I think the simplest approach is just to rebuild the assets and commit it on each release. Also, some info on the README about this could be added, informing that the non-stable branches should be tested with `WP_DEBUG`, and eventually add the documentation about the build step (`npm run build`).

**Comment by pedro-mendonca** [comment]
Some context and past about the current minified assets:
https://github.com/GlotPress/GlotPress/issues/505

**Comment by pedro-mendonca** [comment]
After a deploy to .org that didn't include the minified versions of the recent JS and CSS changes, I think is urgent to add a build process somewhere.
While this isn't decided, I think at least the action Deploy to WP.org should include the build script.
