### ISSUE TITLE
Incorrect plural settings for ky

### ISSUE THREAD

**Issue by tobifjellner** [GlotPress/GlotPress-WP#1633]
Currently (2023-06-08) in GlotPress/locales/locales.php, the parameters for Kyrgyz are:

```
		$kir = new GP_Locale();
		$kir->english_name = 'Kyrgyz';
		$kir->native_name = 'Кыргызча';
		$kir->lang_code_iso_639_1 = 'ky';
		$kir->lang_code_iso_639_2 = 'kir';
		$kir->lang_code_iso_639_3 = 'kir';
		$kir->country_code = 'kg';
		$kir->wp_locale = 'kir';
		$kir->slug = 'kir';
		$kir->nplurals = 1;
		$kir->plural_expression = '0';
		$kir->google_code = 'ky';
		$kir->alphabet = 'cyrillic';

```
However, several sources indicate that the plural parameters should be the same as for English.

1. 
http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

```
ky 	Kyrgyz 	nplurals=2; plural=(n != 1);
```

2.
https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#ky

```
one => n = 1
"other" includes 0
```

3.
CLDR (per https://php-gettext.github.io/Languages/ )

`n != 1
`

**Comment by ocean90** [comment]
I'd like to get some confirmation from the current locale team. Was there a request somewhere? Since the locale is 100% translated in WordPress this will be a huge change and I'd like to get this a bit coordinated.

This doesn't mean that this blocks the request since WordPress.org has it's own locales file.
