### ISSUE TITLE
Consider splitting some templates

### ISSUE THREAD

**Issue by yoavf** [GlotPress/GlotPress-WP#689]
While exploring some design ideas, I realized how hard it is do customize the translation row (preview & editor) in a custom theme because (among other things) the templates are so large.

While we're probably going to change a lot of this with [the new design](https://github.com/GlotPress/GlotPress-WP/projects/2), I'd like to propose starting by splitting some of our templates where possible, especially the translation row. 

Thoughts?

**Comment by ocean90** [comment]
Hey @yoavf, thanks for all your recent issues. I see that you've already found the project which I recreated today. The new design project is not just a regular design update like improving the current templates. It's something bigger than this.

As [already said a few months ago](https://wordpress.slack.com/archives/glotpress/p1473183798000091), the two projects - [New Design](https://github.com/GlotPress/GlotPress-WP/projects/2) and [REST API ](https://github.com/GlotPress/GlotPress-WP/projects/3) - are linked together: The new design/UI should be build on top of the REST API.

**Comment by toolstack** [comment]
I've avoid doing too much work on the "design" for GP as the new design will likely be significantly different so it seems like a waste of effort in general.  

I wouldn't be for doing this at this time only as it would have a pretty major impact on anyone who has modified the theme.  If we're going to break it, I'd rather break it once instead of twice.

**Comment by yoavf** [comment]
Was done with #913
