### ISSUE TITLE
Discarding Warning (for URL missing) causes duplicate entry until reload

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#699]
Hello,

If you get a warning for say URL missing in translated string (which happens if you localize a plugin URL) then you'll get a warning;
![screen shot 2017-04-12 at 11 22 59 am](https://cloud.githubusercontent.com/assets/8726005/25021041/9cbd2ac8-2045-11e7-875b-295fe60d34ee.png)

If you discard this warning then the translation becomes approved (green) but a duplicate is created which is open for editing;
![screen shot 2017-04-12 at 11 33 24 am](https://cloud.githubusercontent.com/assets/8726005/25021050/a1ec650e-2045-11e7-8ee3-a9d474a9f6cd.png)

This is minor, if you reload then the duplicate disappears, but if you were to approve the second string before reload could create some conflict (that's a presumption I didn't actually test that part).

Let me know if I can clarify or assist,
Cheers

**Comment by toolstack** [comment]
Found the issue, it's actually not a duplicate entry, just that the "preview" row and the "editor" row are both being displayed at the same time.

I've created a PR to resolve and also updated the behaviour of the dismiss action so that it moves to the next translation (assuming all errors are clear) just like the "Add translation" button does.
