### ISSUE TITLE
Starting Newline stripped from Translation

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#701]
Hello,

While translating the iOS app I came across the following entry which had a requirement of the first character being a newline;
![screen shot 2017-04-17 at 11 55 25 am](https://cloud.githubusercontent.com/assets/8726005/25100393/c2c70596-2364-11e7-8407-944c2c6ad909.png)
Permalink - https://translate.wordpress.org/projects/apps/ios/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4334240&filters%5Btranslation_id%5D=48678505

If you copy the original and submit as a translation the initial newline character is stripped on submit and triggers the warning as the first character is no longer a newline.

Cheers

**Comment by toolstack** [comment]
Found the issue, this is a jquery issue, from the [jquery val()](http://api.jquery.com/val/) page:
![jquery-val](https://cloud.githubusercontent.com/assets/9053749/25871301/0a195a6c-34d5-11e7-98e9-1206c47b371b.png)

Adding the additional hook fixed submitting the newline, but GP didn't display it afterwards correctly.  This is because of we have to "escape" beginning line breaks with an additional line break for browsers to display it correctly (see [this](https://forum.phalconphp.com/discussion/3573/losing-empty-line-at-beginning-of-textarea-phalcon-tag-textarea-) for more info).

**Comment by garretthyder** [comment]
Thanks @toolstack & @ocean90

**Comment by garretthyder** [comment]
@toolstack is this live on translate.wordpress.org??
I seem to still be experiencing it with this string;
Permalink - https://translate.wordpress.org/projects/wp-plugins/speed-booster-pack/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4609903&filters%5Btranslation_id%5D=50024919

Thanks

**Comment by toolstack** [comment]
@Garrett-eclipse no, it's commuted to the git repo, then we'll do a GP release and the it will be deployed to translate.w.org.

Sometimes @ocean90 will push things out early depending on the importance of it.

**Comment by garretthyder** [comment]
Thanks @toolstack I'll hold on this translation then. Is there a place I can subscribe to get notified when GP is released or deployed to translate.w.org? Appreciated

**Comment by toolstack** [comment]
It usually get announced in the GP channel on slack.

**Comment by garretthyder** [comment]
Cool thanks @toolstack I'll keep my eye on the channel there
