### ISSUE TITLE
Using Browser Back loads translated strings as untranslated

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#714]
Hello,

I just came across this while translating, but if you translate a whole page of strings;
![screen shot 2017-05-09 at 1 01 18 pm](https://cloud.githubusercontent.com/assets/8726005/25870126/d92ec30a-34b7-11e7-8b7b-273499f4ad71.png)

Then go forward a page in the pagination, and using browser back navigate back to the page you just translated you'll find they're all not translated;
![screen shot 2017-05-09 at 1 01 27 pm](https://cloud.githubusercontent.com/assets/8726005/25870148/eba1359a-34b7-11e7-9258-3692868ddcab.png)

Reloading fixes this, and the system blocks you from submitting an identical translation again.

Not sure if it's something that can even be fixed but just wanted to flag if not already aware.

Thanks

**Comment by swissspidy** [comment]
This is really expected behaviour IMHO. Browsers cache your visited web pages, so when you hit backspace, the browser loads the cached version of that page.

[Some resources](http://blog.55minutes.com/2011/10/how-to-defeat-the-browser-back-button-cache/) recommend setting `Cache-Control` headers to prevent this from happening, but that has drawbacks as well.

**Comment by ocean90** [comment]
As Pascal already said, that's kinda expected. Closing as wontfix.

**Comment by garretthyder** [comment]
Sounds good, thanks @swissspidy & @ocean90
