### ISSUE TITLE
Please split pluralized strings into two rows under Original String like the Translation column has

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#760]
Hello,

It would be nice to have the 'Original string' column split into two rows when dealing with a plural string similar to how the 'Translation' column is split so that you can visually match singular and plural strings with their translation.
Helps when doing bulk approvals

Screen;
![screen shot 2017-06-28 at 3 52 11 pm](https://user-images.githubusercontent.com/8726005/27663983-f445441e-5c19-11e7-9bfd-f10f27e23cab.png)

Thank you

**Comment by tobifjellner** [comment]
I believe that it may be useful to see both forms in the string in the source language. But to "visually pair" may not work that well. There are languages that simply don't have plural forms. And there are languages where every plural-capable string has to be translated to 3 (Russian, Polish...) or even 4 (Maltese) versions.

**Comment by garretthyder** [comment]
Thanks @tobifjellner that's good to know, I'm an english variant translator so am unaware of alot of those global nuances. I think the source if plural would be good to split and then I guess depending on the language the result could be split into up to 4 rows?

**Comment by toolstack** [comment]
Plurals are a little strange that way and adding the plural form to the list may in fact just confuse things.

For example the default gettext process is to have a singular and a plural form in the php functions (aka n=2) but there are languages that still have n=2 but with different plural forms for those two strings.

In that case you'd "visually" see the original and plural match, but they may not be used in the same way.

Likewise adding additional original strings to the left side might get messy and visually confusing.

I would say that this is a `wontfix` case, @ocean90 any thoughts?

**Comment by ocean90** [comment]
That won't work because we currently don't know which original form a translation is using.

Take this as an example: https://translate.wordpress.org/projects/wp/dev/admin/ru/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=231228&filters%5Btranslation_id%5D=22143579 At the moment you can't tell if the second and third form is using the singular or plural form.
Same for locales with 6 forms https://translate.wordpress.org/projects/wp/dev/admin/ar/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=231228&filters%5Btranslation_id%5D=21368834 with 6 forms.

**Comment by garretthyder** [comment]
Thanks guys, I see what you're saying there makes sense.
