### ISSUE TITLE
Glossary terms with special characters aren't detected

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#762]
Hello,

I just noticed the cheating message 'huh?' isn't picked up even though it's in the glossary.
Permalink - https://translate.wordpress.org/projects/wp-plugins/press-elements/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4691707&filters%5Btranslation_id%5D=50376530

This is for en_CA btw, here's glossary;
https://translate.wordpress.org/locale/en-ca/default/glossary

Cheers

**Comment by toolstack** [comment]
That's because we use the following regex to match terms:

```
preg_match( '/\b(' . $terms . ')\b/i', $t->singular . ' ' . $t->plural, $m ) 
```
the `\b` in there is any word break characters, which includes all punctuation, so when you add punctuation in to the term, it never gets matched as it's included as part of the `\b`.

For example, the string "Cheating huh?" get's parsed in to "Cheating" and "huh", so a glossary term of "huh?" does not match.

We can't convert the `\b` on to something like `[\b\s\Z]` as `\b` inside a character class represents a backspace and there is no equivalent word boundary delimiter for character classes.

I think the solution to this one is "don't put punctuation in glossary terms."

**Comment by garretthyder** [comment]
Thanks @toolstack that's probably the best as there'll be instances without the punctuation so dropping it would cover both instances without and with the exclamation.
I've updated en_CA Glossary;
https://translate.wordpress.org/locale/en-ca/default/glossary

Although I see this in en_AU for their Howdy!;
![screen shot 2017-06-30 at 9 22 58 am](https://user-images.githubusercontent.com/8726005/27744787-c72a8b3a-5d75-11e7-89dc-bff97ef8ff65.png)
Sadly I am not a GTE for that locale or any other english variants to fix them, so will flag in Slack #meta-i18n in hopes of getting their attention.

I've also setup a ticket to block with warning any Glossary Terms that contain punctuation - #768
* @toolstack just to confirm this wouldn't affect works like G'day or tool-bar where the character is within the word?

Thanks

**Comment by toolstack** [comment]
`\b` should only catch word breaks, so characters like `'` should not be included. I tested `'` and it matches file.

**Comment by garretthyder** [comment]
Nice, thanks @toolstack
