### ISSUE TITLE
Grant admin permission to users from WordPress dashboard

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#803]
Looking at https://glotpress.blog/the-manual/admin-users/ it is suggested to do a sql query to grant permission to users.
I was expecting something from the WordPress dashboard instead. Like in this screen.

![screenshot_20170826_163651](https://user-images.githubusercontent.com/403283/29742297-d589cff4-8a7c-11e7-8b3a-cba5d715e281.png)

I can work on that in case because the installation of GlotPress seems very uncomfortable and not simple also for me that I am a developer.

**Comment by Mte90** [comment]
Also probably show a reminder inside the dashboard that also if you are an admin you are not a glotpress admin.

**Comment by swissspidy** [comment]
My understanding of GlotPress as a plugin so far has been that people shouldn't really know it's running on WordPress. That's why there aren't any signs of it in the admin as you should be able to do everything on the front end.

I might be wrong about it, but for me it would make more sense to have such a thing available either via CLI or in some kind of front-end admin area.

**Comment by Mte90** [comment]
Uhm probably I agree with you but at least for the installation or setup of GlotPress that part should be in WordPress because after all is a plugin.

**Comment by toolstack** [comment]
You can already grant GP admin rights through the WP user profile screen:

![gp-admin](https://user-images.githubusercontent.com/9053749/29743286-d63a7252-8a5c-11e7-8b49-5c677973b25e.png)

The admin manual just needs to be updated.

**Comment by toolstack** [comment]
I've updated the admin manual as well.
