### ISSUE TITLE
Fix risky tests

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#841]
```
There were 4 risky tests:

1) GP_Test_Permissions::test_create_find
This test did not perform any assertions

2) GP_Test_Permissions::test_create_find_with_nulls
This test did not perform any assertions

3) GP_Test_Thing_Translation::test_translation_should_support_6_plurals
This test did not perform any assertions

4) GP_Test_Thing_Translation::test_translation_should_write_all_6_plurals_to_database
This test did not perform any assertions

OK, but incomplete, skipped, or risky tests!
Tests: 334, Assertions: 1245, Skipped: 2, Risky: 4.
```

**Comment by toolstack** [comment]
It looks like the above 4 risky tests have been fixed at some point as they no longer report.

However looking at the 2 skipped tests there is a bug in one of them and the second shouldn't really be reported as a skipped test but is due to an artefact on extending the PO test class as a base for the MO test class.

PR #937 fixed the two above skipped tests and produces a clean output from PHPUnit.
