### ISSUE TITLE
Suppress Duplicate Comments

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#929]
When a string is found numerous places in the project it can be supplemented with a comment.

If those comments are all identical it would make sense to suppress them instead of repeating numerous times;
![screen shot 2018-09-26 at 11 38 24 am](https://user-images.githubusercontent.com/8726005/46101418-b3b8af80-c180-11e8-9643-381d6ac508f0.png)

The above string is here - https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6617369&filters%5Btranslation_id%5D=57390744

**Comment by toolstack** [comment]
GP doesn't really handle the comments, we just use whatever the WP PO/MO code gives us, which really just uses whatever is in the source POT file.

Ideally the duplicates should be removed before they are imported in to GP.

**Comment by toolstack** [comment]
I took a deeper look at this and am going to close it as `wontfix` for two primary reasons:

- If we try and detect duplicate entries after the import/display as part of GP, then we may get in to the situation where we inadvertently change the mean of a comment due to removing a "duplicate" line that is actually important.  It would seem like a better idea to err on the side of caution in this situation.
- as I mentioned above, this is really something that should be fixed in the source POT file when it is created, so for WP in the string extractor contained in core.

**Comment by garretthyder** [comment]
Thanks @toolstack I've opened this on Meta Trac to address for translate.wp.org, if you have any additional thoughts or pointers please add to the ticket.
Meta Trac Ticket - https://meta.trac.wordpress.org/ticket/3856
