### ISSUE TITLE
Notes: Don't escape notes when inserting, use sanitization

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#998]
Noticed that `esc_html()` is used before inserting the note in https://github.com/GlotPress/GlotPress-WP/blob/ffecc3c/gp-includes/things/note.php#L77.
Only the output should be escaped, when storing the data needs to be sanitized. More importantly, `GP_Route_Note::edit_post()` and `GP_Note::edit()` doesn't do both.

`wp_kses()` with a predefined list of allowed tags should be used. See also `wp_kses_allowed_html()`.

**Comment by Mte90** [comment]
So you are suggesting to sanitize also on https://github.com/GlotPress/GlotPress-WP/blob/ffecc3c/gp-includes/things/note.php#L103
Instead https://github.com/GlotPress/GlotPress-WP/blob/ffecc3c1e1/gp-includes/routes/note.php#L71 we are sending the value to edit of the other method so we can avoid to sanitize twice.

I am wondering why use `wp_kses` instead `esc_html`? because we don't want HTML tags that can be used there, `wp_kses` is used to cleanup and keep few of them.

**Comment by ocean90** [comment]
`wp_kses(  $note, [] );` will remove all tags, `esc_html()` only escapes them.

**Comment by ocean90** [comment]
The notes features has been reverted for now, see #1046.
